package com.artuhin.project.dao;

import com.artuhin.project.model.Appointment;
import com.artuhin.project.model.EMailData;
import com.artuhin.project.model.Procedure;
import com.artuhin.project.util.rsparser.WithoutReflectionParser;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class AppointmentsDao {

    private static Logger LOGGER = LogManager.getLogger(AppointmentsDao.class);
    private final String SQL_EXCEPTION = "SQL exception Report DAO";

    public int create(Appointment appointment) {
        int autoGeneratedId = 0;
        if (checkIfExists(appointment)) {
            return autoGeneratedId;
        }
        String CREATE_SQL = "INSERT INTO appointments (procedure_name, master_login, client_login, start_time, is_confirmed, is_paid_up, is_finished, is_rated) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(CREATE_SQL, Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setString(1, appointment.getProcedure().getName());
            preparedStatement.setString(2, appointment.getMasterLogin());
            preparedStatement.setString(3, appointment.getClientLogin());
            preparedStatement.setTimestamp(4, appointment.getStartTime());
            preparedStatement.setBoolean(5, appointment.isConfirmed());
            preparedStatement.setBoolean(6, appointment.isPaidUp());
            preparedStatement.setBoolean(7, appointment.isFinished());
            preparedStatement.setBoolean(8, appointment.isRated());
            System.out.println();
            preparedStatement.executeUpdate();
            ResultSet id = preparedStatement.getGeneratedKeys();
            id.next();
            autoGeneratedId = id.getInt(1);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return autoGeneratedId;
    }

    public boolean checkIfExists(Appointment appointment) {
        List<Appointment> appointments;
        String GET_APPOINTMENTS = "SELECT * FROM appointments WHERE master_login = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_APPOINTMENTS)) {
            String login = appointment.getMasterLogin();
            preparedStatement.setString(1, login);
            appointments = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
            for (Appointment appointmentTemp : appointments) {
                if (appointment.getStartTime().getTime() >= appointmentTemp.getStartTime().getTime()
                        && appointment.getStartTime().getTime() <= (appointmentTemp.getStartTime().getTime() + appointmentTemp.getProcedure().getDuration())
                        || (appointment.getStartTime().getTime() + appointment.getProcedure().getDuration()) >= appointmentTemp.getStartTime().getTime()
                        && (appointment.getStartTime().getTime() + appointment.getProcedure().getDuration()) <= (appointmentTemp.getStartTime().getTime() + appointmentTemp.getProcedure().getDuration())) {
                    return true;
                }
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return false;
    }

    public boolean update(Appointment appointment) {
        String UPDATE_SQL = "UPDATE appointments SET procedure_name = ?, master_login = ?, client_login = ?, start_time = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setString(1, appointment.getProcedure().getName());
            preparedStatement.setString(2, appointment.getMasterLogin());
            preparedStatement.setString(3, appointment.getClientLogin());
            preparedStatement.setTimestamp(4, appointment.getStartTime());
            preparedStatement.setLong(5, appointment.getId());
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean delete(long id) {
        String DELETE_SQL = "DELETE FROM appointments WHERE id = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(DELETE_SQL)) {
            preparedStatement.setLong(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public Appointment getByID(long id) {
        Appointment appointment = new Appointment();
        String GET_BY_ID_SQL = "SELECT * FROM appointments WHERE id = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_BY_ID_SQL)) {
            preparedStatement.setLong(1, id);
            appointment = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery()).get(0);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return appointment;
    }

    public List<Appointment> getAll() {
        List<Appointment> resultList = new ArrayList<>();
        String GET_ALL_SQL = "SELECT * FROM appointments";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ALL_SQL)) {
            resultList = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    public boolean clearAll() {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             Statement statement = connectionProxy.createStatement()) {
            String CLEAR_ALL_SQL = "DELETE * FROM appointments";
            statement.executeUpdate(CLEAR_ALL_SQL);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public List<Appointment> getAppointmentsByClientLogin(String login) {
        List<Appointment> appointments = new ArrayList<>();
        String GET_APPOINTMENTS_BY_CLIENT_ID_SQL = "SELECT * FROM appointments WHERE client_login = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_APPOINTMENTS_BY_CLIENT_ID_SQL)) {
            preparedStatement.setString(1, login);
            appointments = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
            System.out.println();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return appointments;
    }

    public List<Appointment> getAppointmentByMasterLogin(String login) {
        List<Appointment> appointments = new ArrayList<>();
        String GET_APPOINTMENTS_BY_MASTER_ID_SQL = "SELECT * FROM appointments WHERE master_login = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_APPOINTMENTS_BY_MASTER_ID_SQL)) {
            preparedStatement.setString(1, login);
            appointments = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return appointments;
    }

    public List<Appointment> getAppointmentByMasterLoginByDay(String login, int day) {
        List<Appointment> appointments = new ArrayList<>();
        List<Appointment> returnAppointments = new ArrayList<>();
        String GET_APPOINTMENTS_BY_MASTER_ID_SQL = "SELECT * FROM appointments WHERE master_login = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_APPOINTMENTS_BY_MASTER_ID_SQL)) {
            preparedStatement.setString(1, login);
            appointments = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
            returnAppointments = new ArrayList<>();
            for (Appointment appointment : appointments) {
                if (appointment.getStartTime().toLocalDateTime().getDayOfYear() == day) {
                    returnAppointments.add(appointment);
                }
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return returnAppointments;
    }

    public boolean updateConfirmToTrue(long id) {
        String UPDATE_SQL = "UPDATE appointments SET is_confirmed = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setBoolean(1, true);
            preparedStatement.setLong(2, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean updatePaidUpToTrue(long id) {
        String UPDATE_SQL = "UPDATE appointments SET is_paid_up = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setBoolean(1, true);
            preparedStatement.setLong(2, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean updateStartTime(Long id, LocalTime localTime) {
        Appointment appointment = getByID(id);
        Appointment exist = getByID(id);
        Timestamp timestamp = appointment.getStartTime();
        LocalDate localDate = timestamp.toLocalDateTime().toLocalDate();
        LocalDateTime newLDT = LocalDateTime.of(localDate, localTime);
        appointment.setStartTime(Timestamp.valueOf(newLDT));
        if (checkIfExists(appointment, exist)) {
            return false;
        }
        String UPDATE_SQL = "UPDATE appointments SET start_time = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setTimestamp(1, appointment.getStartTime());
            preparedStatement.setLong(2, appointment.getId());
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean checkIfExists(Appointment checked, Appointment exist) {
        List<Appointment> appointments;
        String GET_APPOINTMENTS = "SELECT * FROM appointments WHERE master_login = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_APPOINTMENTS)) {
            String login = checked.getMasterLogin();
            preparedStatement.setString(1, login);
            appointments = WithoutReflectionParser.getInstance().appointmentsParser(preparedStatement.executeQuery());
            appointments.remove(exist);
            for (Appointment appointmentTemp : appointments) {
                if (checked.getStartTime().getTime() >= appointmentTemp.getStartTime().getTime()
                        && checked.getStartTime().getTime() <= (appointmentTemp.getStartTime().getTime() + appointmentTemp.getProcedure().getDuration())
                        || (checked.getStartTime().getTime() + checked.getProcedure().getDuration()) >= appointmentTemp.getStartTime().getTime()
                        && (checked.getStartTime().getTime() + checked.getProcedure().getDuration()) <= (appointmentTemp.getStartTime().getTime() + appointmentTemp.getProcedure().getDuration())) {
                    return true;
                }
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return false;
    }

    public boolean updateFinishedToTrue(long id) {
        String UPDATE_SQL = "UPDATE appointments SET is_finished = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setBoolean(1, true);
            preparedStatement.setLong(2, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public List<EMailData> getDataForNotifications(Timestamp timestamp) {
        List<EMailData> eMailDatas = new ArrayList<>();
        List<Appointment> appointments = getAll();
        for (Appointment a : appointments) {
            if (a.getStartTime().toLocalDateTime().getDayOfYear() + 1 == timestamp.toLocalDateTime().getDayOfYear() && a.isFinished() && !a.isRated()) {
                EMailData eMailData = new EMailData();
                eMailData.setAppointmentId(a.getId());
                eMailData.setMasterLogin(a.getMasterLogin());
                eMailData.setProcedureName(a.getProcedure().getName());
                eMailData.setUserLogin(a.getClientLogin());
                eMailData.setTimestamp(a.getStartTime());
                eMailDatas.add(eMailData);
            }
        }
        return eMailDatas;
    }

    public boolean updateRatedToTrue(long id) {
        String UPDATE_SQL = "UPDATE appointments SET is_rated = ? WHERE id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setBoolean(1, true);
            preparedStatement.setLong(2, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }
}

