package com.artuhin.project.dao;

import com.artuhin.project.model.Procedure;
import com.artuhin.project.util.rsparser.ResultSetParser;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class ProcedureAo {
    private static Logger LOGGER = LogManager.getLogger(ProcedureAo.class);
    private final String SQL_EXCEPTION = "SQL exception user DAO";

    public Procedure getById(int id) {
        Procedure procedure = new Procedure();
        int autoGeneratedId = 0;
        String CREATE_SQL = "SELECT FROM procedures WHERE id = ?)";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(CREATE_SQL, Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setInt(1, id);
            procedure = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new Procedure()).get(0);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return procedure;
        }
        return procedure;
    }

}
