-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

BEGIN;

drop table if exists users cascade;

drop table if exists events cascade;

drop table if exists role cascade;

drop table if exists procedures cascade;


CREATE TABLE public.role
(
    id bigserial NOT NULL,
    name character varying(32) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id bigserial NOT NULL,
    role_id integer NOT NULL,
    login character varying(32) NOT NULL,
    password character varying(64) NOT NULL,
    rating integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.procedures
(
    id bigserial NOT NULL,
    name character varying(64) NOT NULL,
    duration bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.events
(
    id bigserial NOT NULL,
    procedure_id bigint NOT NULL,
    master_id bigint NOT NULL,
    client_id bigint NOT NULL,
    start_time timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.events
    ADD FOREIGN KEY (procedure_id)
        REFERENCES public.procedures (id)
        NOT VALID;


ALTER TABLE public.events
    ADD FOREIGN KEY (master_id)
        REFERENCES public.users (id)
        NOT VALID;


ALTER TABLE public.events
    ADD FOREIGN KEY (client_id)
        REFERENCES public.users (id)
        NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (role_id)
        REFERENCES public.role (id)
        NOT VALID;

END;